version: "3.7"

services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: sample-app
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - sample-app-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - sample-app-redis:/var/lib/redis/data

  sample-app:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./sample-app
        target: /opt/app/sample-app
    ports:
      - '3000:3000'
    env_file:
      - .env

  puma:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec puma
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./sample-app
        target: /opt/app/sample-app
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - sample-app
    ports:
      - '8020:8020'

volumes:
  sample-app-postgres:
  sample-app-redis: